# Site settings
author: Haoyang Yu
title: Haoyang's Blog
header-img: img/home-bg.png
email: haoyangy@middlebury.edu
copyright_name: Haoyang Yu
description: > # this means to ignore newlines until "baseurl:"
  space-out
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hy123udg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
